"""Default Peterson + Goliath profiles. Differ only in JSON."""

PETERSON_ROOF = {
    "client_tag": "peterson_roof",
    "display_name": "Peterson roofing GCs",
    "geo": {
        "country": "US",
        "states": ["TX"],
        "cities": [
            "Dallas",
            "Fort Worth",
            "Arlington",
            "Plano",
            "Irving",
            "Garland",
            "Frisco",
            "McKinney",
            "MCKINNEY",
            "Grand Prairie",
            "Mesquite",
            "Denton",
            "Richardson",
            "RICHARDSON",
            "Carrollton",
            "Lewisville",
            "Allen",
            "ALLEN",
            "Mansfield",
            "Rowlett",
            "Euless",
            "DeSoto",
            "Desoto",
            "Grapevine",
            "Bedford",
            "Cedar Hill",
            "Keller",
            "Coppell",
            "Hurst",
            "The Colony",
            "Rockwall",
            "Wylie",
            "WYLIE",
            "Little Elm",
            "Haltom City",
            "Burleson",
            "Farmers Branch",
            "Duncanville",
            "Lancaster",
            "North Richland Hills",
            "Nrh",
            "Southlake",
            "Colleyville",
            "Addison",
            "Murphy",
            "MURPHY",
            "Prosper",
            "PROSPER",
            "Celina",
            "CELINA",
            "Melissa",
            "MELISSA",
            "Anna",
            "ANNA",
            "Princeton",
            "PRINCETON",
            "PLANO",
            "FRISCO",
        ],
        "area_codes": ["214", "469", "972", "817", "682", "940", "903", "254", "430", "945"],
        "center_lat": 32.7767,
        "center_lng": -96.7970,
        "radius_mi": 80,
        "geo_required": True,
    },
    "name_strip_tokens": [
        "inc",
        "llc",
        "ltd",
        "co",
        "corp",
        "company",
        "group",
        "services",
        "construction",
        "contractors",
        "builders",
    ],
    "industry_reject_regex": (
        "roof|hvac|plumb|electric|paint|storage|interior|design|"
        "landscap|fence|pool|sign|concrete|glass"
    ),
    "industry_allow_regex": None,
    "aggregator_blocklist": [],
    "tld_allow": [".com", ".net", ".org", ".us", ".co", ".io", ".biz", ".build", ".construction"],
    "name_reject_regex": (
        "horton|lennar|pulte|kb home|meritage|toll brothers|weekley|"
        "highland homes|first texas|centex|ryland|d\\.r\\. horton"
    ),
    "ground_truth": {
        "table": "client_peterson.gc_adjudication",
        "where": "lane = 'commercial_gc'",
    },
    "domain_cache_tables": ["gc.companies"],
    "second_opinion": False,
    "enabled_tiers": [
        "cache",
        "maps",
        "aiark",
        "discolike",
        "serp",
        "prospeo",
        "leadmagic",
    ],
}

GOLIATH = {
    "client_tag": "goliath",
    "display_name": "Goliath IT 50-300",
    "geo": {
        "country": "US",
        "states": [],
        "cities": [],
        "area_codes": [],
        "center_lat": None,
        "center_lng": None,
        "radius_mi": None,
        "geo_required": False,
    },
    "name_strip_tokens": [
        "inc",
        "llc",
        "ltd",
        "co",
        "corp",
        "company",
        "group",
        "services",
    ],
    "industry_reject_regex": None,
    "industry_allow_regex": None,
    "aggregator_blocklist": [],
    "tld_allow": [".com", ".net", ".org", ".us", ".co", ".io", ".biz"],
    "ground_truth": {
        "table": "public.goliath_wf_companies",
        "where": "domain is not null",
    },
    "domain_cache_tables": ["public.goliath_wf_companies"],
    "second_opinion": False,
    "enabled_tiers": [
        "cache",
        "maps",
        "aiark",
        "discolike",
        "serp",
        "prospeo",
        "leadmagic",
    ],
}
